---
- name: 'Install NFS'
  apt:
    name: 'nfs-kernel-server'

- name: 'Configure exports'
  template:
    src: 'exports'
    dest: '/etc/exports'
  when:   "nfs_exports != ''"
  notify: 'nfs_reload'

- name: 'Configure firewall'
  ufw:
    rule: 'allow'
    port: 'nfs'
...
